language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
before_install:
  - sudo apt-get update
  - sudo apt-get install python-setuptools python-pygame python-opengl python-gst0.10 python-enchant gstreamer0.10-plugins-good python-dev build-essential libgl1-mesa-dev libgles2-mesa-dev

install:
  - pip install --upgrade cython pil --use-mirrors
  - make

# command to run tests
script:
  - make test
